/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAuth {
    }
    interface AppDevices {
    }
    interface AppGuide {
    }
    interface AppHome {
    }
    interface AppNewGuide {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAuthElement extends Components.AppAuth, HTMLStencilElement {
    }
    var HTMLAppAuthElement: {
        prototype: HTMLAppAuthElement;
        new (): HTMLAppAuthElement;
    };
    interface HTMLAppDevicesElement extends Components.AppDevices, HTMLStencilElement {
    }
    var HTMLAppDevicesElement: {
        prototype: HTMLAppDevicesElement;
        new (): HTMLAppDevicesElement;
    };
    interface HTMLAppGuideElement extends Components.AppGuide, HTMLStencilElement {
    }
    var HTMLAppGuideElement: {
        prototype: HTMLAppGuideElement;
        new (): HTMLAppGuideElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppNewGuideElement extends Components.AppNewGuide, HTMLStencilElement {
    }
    var HTMLAppNewGuideElement: {
        prototype: HTMLAppNewGuideElement;
        new (): HTMLAppNewGuideElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-auth": HTMLAppAuthElement;
        "app-devices": HTMLAppDevicesElement;
        "app-guide": HTMLAppGuideElement;
        "app-home": HTMLAppHomeElement;
        "app-new-guide": HTMLAppNewGuideElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAuth {
    }
    interface AppDevices {
    }
    interface AppGuide {
    }
    interface AppHome {
    }
    interface AppNewGuide {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-auth": AppAuth;
        "app-devices": AppDevices;
        "app-guide": AppGuide;
        "app-home": AppHome;
        "app-new-guide": AppNewGuide;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-auth": LocalJSX.AppAuth & JSXBase.HTMLAttributes<HTMLAppAuthElement>;
            "app-devices": LocalJSX.AppDevices & JSXBase.HTMLAttributes<HTMLAppDevicesElement>;
            "app-guide": LocalJSX.AppGuide & JSXBase.HTMLAttributes<HTMLAppGuideElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-new-guide": LocalJSX.AppNewGuide & JSXBase.HTMLAttributes<HTMLAppNewGuideElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
